site_name: cuthbert
site_url: https://state-space-models.github.io/cuthbert
repo_url: https://github.com/state-space-models/cuthbert

theme:
  name: material
  logo: assets/cuthbert.png
  favicon: assets/cuthbert_c.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - content.code.copy
    - navigation.indexes

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Contributing: contributing.md
  - cuthbert API:
    - api/cuthbert/index.md
    - api/cuthbert/filtering.md
    - api/cuthbert/smoothing.md
    - Discrete HMMs: api/cuthbert/discrete.md
    - Gaussian filters and smoothers:
      - Exact Kalman: api/cuthbert/gaussian/kalman.md
      - Extended Kalman: api/cuthbert/gaussian/extended_kalman.md
    - Sequential Monte Carlo:
      - api/cuthbert/smc/index.md
      - api/cuthbert/smc/backward_sampler.md
      - api/cuthbert/smc/marginal_particle_filter.md
      - api/cuthbert/smc/particle_filter.md
      - api/cuthbert/smc/types.md
  - cuthbertlib API:
    - api/cuthbertlib/index.md
    - api/cuthbertlib/backward_sampling.md
    - api/cuthbertlib/kalman.md
    - api/cuthbertlib/linearize.md
    - Quadrature Methods: api/cuthbertlib/quadrature.md
    - api/cuthbertlib/resampling.md
    - api/cuthbertlib/stats.md
    - api/cuthbertlib/types.md

plugins:
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_symbol_type_heading: true
            members_order: source
            show_if_no_docstring: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
