[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cuthbert"
version = "0.0.1"
description = "State-space model inference with JAX"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "Apache-2.0" }
authors = [
    { name = "Sam Duffield", email = "s@mduffield.com" },
    { name = "Adrien Corenflos", email = "adrien.corenflos.stats@gmail.com" },
]

dependencies = [
    "jax>=0.4.35",
    "numba>=0.60.0",
]

[tool.setuptools.packages.find]
include = ["cuthbert", "cuthbertlib"]

[project.optional-dependencies]
test = [
    "chex",  # test additional dependencies
    "pre-commit", "ruff", "pyright",  # linting etc
    "pytest", "pytest-xdist",  # testing
]

[tool.ruff]
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F821", "E402"]
