[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cuthbert"
version = "0.0.1"
description = "State-space model inference with JAX"
readme = "README.md"
requires-python =">=3.9"
license = {text = "Apache-2.0"}
authors = [
    {name = "Sam Duffield", email = "s@mduffield.com"},
    {name = "Adrien Corenflos", email = "adrien.corenflos.stats@gmail.com"},
]

dependencies = [
    "jax>=0.4.26",
]

[project.optional-dependencies]
test = ["pre-commit", "ruff", "pyright", "pytest"]

[tool.ruff]
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F821", "E402"]
